import type { Metadata } from "next";
import "./globals.css";
import { AI } from "./action";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AI>
      <html lang='en'>
        <body>{children}</body>
      </html>
    </AI>
  );
}
